// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, ConditionalPaginatedResultMixed, InferResult, SortString, TaskFilterInput, TaskResourceSchema, TaskSortField, UUID, UnifiedFieldSelection } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any> | undefined;
  identity?: any;
  fields?: Array<string | Record<string, any>> | undefined; // Field selection
  filter?: Record<string, any> | undefined; // Filter options (for reads)
  sort?: string | string[] | undefined; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      }
    | undefined;

  // Metadata
  metadataFields?: ReadonlyArray<string> | undefined;

  // HTTP customization
  headers?: Record<string, string> | undefined; // Custom headers
  fetchOptions?: RequestInit | undefined; // Fetch options (signal, cache, etc.)
  customFetch?: ((
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>) | undefined;

  // Multitenancy
  tenant?: string | undefined; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any> | undefined;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}









export type CreateTaskInput = {
  title: string;
  notes?: string | null;
  status?: "done" | "open";
};

export type CreateTaskFields = UnifiedFieldSelection<TaskResourceSchema>[];

export type InferCreateTaskResult<
  Fields extends CreateTaskFields | undefined,
> = InferResult<TaskResourceSchema, Fields>;

export type CreateTaskResult<Fields extends CreateTaskFields | undefined = undefined> = | { success: true; data: InferCreateTaskResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Task
 *
 * @ashActionType :create
 */
export async function createTask<Fields extends CreateTaskFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: CreateTaskInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CreateTaskResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "create_task",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<CreateTaskResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


export type DestroyTaskResult = | { success: true; data: {}; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Delete a Task
 *
 * @ashActionType :destroy
 */
export async function destroyTask(
  config: {
  tenant?: string;
  identity: UUID;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<DestroyTaskResult> {
  const payload = {
    action: "destroy_task",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeActionRpcRequest<DestroyTaskResult>(
    payload,
    config
  );
}


export type ListTasksFields = UnifiedFieldSelection<TaskResourceSchema>[];


export type InferListTasksResult<
  Fields extends ListTasksFields | undefined,
  Page extends ListTasksConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<TaskResourceSchema, Fields>>, {
  results: Array<InferResult<TaskResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<TaskResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string | null;
  nextPage: string | null;
  count?: number | null;
  type: "keyset";
}>;

export type ListTasksConfig = {
  tenant?: string;
  fields: ListTasksFields;
  filter?: TaskFilterInput;
  sort?: SortString<TaskSortField> | SortString<TaskSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListTasksResult<Fields extends ListTasksFields, Page extends ListTasksConfig["page"] = undefined> = | { success: true; data: InferListTasksResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Task records
 *
 * @ashActionType :read
 */
export async function listTasks<Fields extends ListTasksFields, Config extends ListTasksConfig = ListTasksConfig>(
  config: Config & { fields: Fields }
): Promise<ListTasksResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_tasks",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListTasksResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


export type UpdateTaskInput = {
  title?: string;
  notes?: string | null;
  status?: "done" | "open";
};

export type UpdateTaskFields = UnifiedFieldSelection<TaskResourceSchema>[];

export type InferUpdateTaskResult<
  Fields extends UpdateTaskFields | undefined,
> = InferResult<TaskResourceSchema, Fields>;

export type UpdateTaskResult<Fields extends UpdateTaskFields | undefined = undefined> = | { success: true; data: InferUpdateTaskResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing Task
 *
 * @ashActionType :update
 */
export async function updateTask<Fields extends UpdateTaskFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  input?: UpdateTaskInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<UpdateTaskResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "update_task",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<UpdateTaskResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}

